---
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: {{ .Values.clustername }}
  namespace: {{ .Values.namespace }}
spec:
  secretBindingName: {{ .Values.secretName }}
  region: {{ .Values.provider.region }}
  purpose: {{ .Values.provider.purpose }}
{{- if eq .Values.provider.name "openstack" }}
  cloudProfileName: converged-cloud
{{- else }}
  cloudProfileName: {{ .Values.provider.name }}
{{- end }}
  provider:
    type: {{ .Values.provider.name }}
    infrastructureConfig:
      apiVersion: {{ .Values.provider.name }}.provider.extensions.gardener.cloud/v1alpha1
{{- if eq .Values.provider.name "openstack" }}
      floatingPoolName: {{ .Values.provider.floatingPoolName }}
{{- end }}
      kind: InfrastructureConfig
      networks:
  {{- if eq .Values.provider.name "aws" }}
        vpc:
          cidr: 10.180.0.0/16
        zones:
          - name: eu-west-1b
            workers: 10.180.0.0/19
            public: 10.180.32.0/20
            internal: 10.180.48.0/20
  {{- else if eq .Values.provider.name "openstack"}}
        workers: 10.180.0.0/16
  {{- end }}
    controlPlaneConfig:
      apiVersion: {{.Values.provider.name}}.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
{{- if eq .Values.provider.name "openstack" }}
      loadBalancerProvider: f5
{{- end }}
    workers:
      - name: worker-1
        minimum: 1
        maximum: 2
        maxSurge: 0
        maxUnavailable: 1
        machine:
          type: {{.Values.provider.imageType}}
          image:
            name: gardenlinux
            #version: 576.3.0
        volume:
          type: gp3
          size: 50Gi
        zones:
          {{ toYaml .Values.provider.worker_zones | nindent 10 }}
        cri:
          name: containerd

  networking:
    type: calico
    nodes: 10.180.0.0/16
  kubernetes:
    version: {{ .Values.provider.kubernetes.version }}
    enableStaticTokenKubeconfig: false
  maintenance:
    autoUpdate:
      kubernetesVersion: false
      machineImageVersion: true
    timeWindow:
      begin: 050000+0200
      end: 060000+0200
  hibernation:
    enabled: {{ .Values.hibernation.enabled }}
    {{- if .Values.hibernation.enabled }}
    schedules:
      {{ toYaml .Values.hibernation.schedules | nindent 6 }}
    {{- else }}
    schedules: []
    {{- end }}
